# 제목과 버전 설정
application:
   version: v0.0.1
   title: 인근주민 청약 프로젝트 화이팅!
   
## 포트번호 수정
server:
   port: 8080

#개발 버전 설정(개발환경인지 운영환경인지)
spring: 
   profiles:
      active: dev # env(운영환경)=> AWS DB or dev(개발환경)=> 컴퓨터자체(localhost) 입력 => DB의 주소가 다르기때문에 저장소가 다르다.
      
      
spring : 
   profiles: dev #개발모드를 의미
   datasource :
      driver-class-name : com.mysql.cj.jdbc.Driver
      url : jdbc:mysql://localhost:3306/(DB테이블명)?useUnicode=true&charaterEncoding=utf-8&serverTimezone=UTC 
      #접속하고 싶은 데이터베이스 url작성
      username : (dbUserName)
      #DBeaver username 작성
      password : (dbPassword)
      #DBeaver password 작성성    
   # JSP 경로 설정
   mvc: 
      view: 
         prefix: /WEB-INF/views/
         suffix: .jsp
      #css,js,image 폴더 위치 설정
      static-path-pattern: /resources/static/**
      
   #yaml 파일 안에 설정을 할 경우 계층표현(상,하위 구분)으로 Tab을 꼭 해주어야한다!