application:
   version: v0.0.1
   title: 인근주민 청약 프로젝트 화이팅!
   
server:
   port: 8080

spring: 
   profiles:
      active: dev
   mvc:
      view: 
         prefix: /WEB-INF/views/
         suffix: .jsp
      static-path-pattern: /resources/static/**
      
mybatis:
  mapper-locations: classpath:/sqlmap/sqlmapper_*.xml
  type-aliases-package: com.ingeunjumin.project.vo
  
pagehelper:
   helper-dialect: mysql
   reasonable: true

---
spring : 
   profiles: dev
   datasource :
      initialization-mode: always
      schema: classpath:init.sql
      driver-class-name : com.mysql.cj.jdbc.Driver
      hikari:
         maximum-pool-size: 2
      url : jdbc:mysql://localhost:3306/applyhome?useUnicode=true&charaterEncoding=utf-8&serverTimezone=UTC 
      username : root
      password : tkddnjs0823
      
      