-- api_test
CREATE TABLE IF NOT EXISTS open_data(
apt_no INT(5) AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT '매매 번호',
deal_amount varchar(20) COMMENT '거래금액',
build_year varchar(5) COMMENT '건축년도',
deal_year varchar(5) COMMENT '계약년도',
road_name varchar(40) COMMENT '도로명',
road_name_bonbun varchar(10) COMMENT '도로명건물본번호코드',
road_name_bunbun varchar(10) COMMENT '도로명건물부번호코드',
road_name_sigungu_code varchar(10) COMMENT '도로명시군구코드',
road_name_seq varchar(5) COMMENT '도로명일련번호코드',
road_name_basement_code varchar(10) COMMENT '도로명지상지하코드',
road_name_code varchar(10) COMMENT '도로명코드',
dong varchar(20) COMMENT '법정동',
bonbun varchar(10) COMMENT '법정동본번코드',
bunbun varchar(10) COMMENT '법정동부번코드',
sigungu_code varchar(10) COMMENT '법정동시군구코드',
eubmyundong_code varchar(10) COMMENT '법정동읍면동코드',
land_code varchar(10) COMMENT '법정동지번코드',
apartment_name varchar(40) COMMENT '아파트명',
deal_month varchar(5) COMMENT '계약월',
deal_day varchar(5) COMMENT '계약일',
serial_number varchar(20) COMMENT '일련번호',
area_for_exclusive_use varchar(10) COMMENT '전용면적',
Jibun varchar(10) COMMENT '지번',
regional_code varchar(5) COMMENT '지역코드',
floor varchar(10) COMMENT '층',
cancel_deal_day varchar(10) COMMENT '해제사유발생일',
cancel_deal_type boolean COMMENT '해제여부'
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;